# Generated by Django 4.1.7 on 2023-02-16 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
